version: "3"
services:
  web:
    image: csic2720_proj
    build: .
    command: "node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
